spring:
  application:
    name: gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8083

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
