# Etapa de build
FROM eclipse-temurin:17-jdk-alpine as build
WORKDIR /app

# Copia tudo do projeto, inclusive os módulos
COPY . .

# Dá permissão de execução ao mvnw
RUN chmod +x ./mvnw

# Compila apenas o módulo do microservice e suas dependências
RUN ./mvnw clean package -DskipTests -pl expense-tracker-microservice -am

# Etapa de runtime
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

# Copia o JAR gerado do módulo específico
COPY --from=build /app/expense-tracker-microservice/target/*.jar app.jar

EXPOSE 8761
ENTRYPOINT ["java", "-jar", "app.jar"]
