spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_tracker
    username: postgres
    password: admin

  docker:
    compose:
      enabled: false

cors:
  allowed-origin: http://localhost:4200

