spring:
  application:
    name: authentication

  jwtSecret: MbxOksa8BHgdAhR80Y3pEYvS5M+MnF2sheFDqprkTqQ4odqoszJLW1ikw64/nT/dTvlgrcBTq7HfK1B9Gai2h5A==
  jwtExpirationMs: 3600000

  redis:
    host: localhost
    port: 6379
    password: redis
    user: redis

  datasource:
    url: jdbc:postgresql://localhost:5432/expense-tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    jpa:
      database-platform: "org.hibernate.dialect.PostgreSQLDialect"
      show-sql: false
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true

    flyway:
      enabled: false
      user: postgres
      password: postgres

server:
  port: 8084

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  internal-api-key: b6484c64-e80f-4f89-9aeb-0b99403c7bce
  internal-operations-key: ab6151e6-9a6a-4db9-aa86-157d044acd43